name: build our images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
#        run: docker buildx build --push --tag slaesh/wpantund:latest --platform linux/amd64,linux/arm/v7,linux/arm64 .
        run: docker buildx build --push --tag slaesh/wpantund:latest --platform linux/arm/v7 .

# EOF
